FROM rasa/rasa-sdk:2.1.2

WORKDIR /app

USER root

RUN python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install rasa==2.1.2

ENV PATH="/opt/venv/bin:$PATH"

COPY ./actions /app/actions

RUN chgrp -R 0 /app && chmod -R g=u /app
USER 1001

VOLUME /tmp

EXPOSE 5005